- name: Print a test message and create a file
  hosts: localhost
  tasks:
    - name: Print a test message
      debug:
        msg: "Test Message: This is a test!"

    - name: Create a test file
      file:
        path: /tmp/testfile.txt
        state: touch
